version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run: sudo pip install codecov
      - python/save-cache
      - run:
          command: sudo python setup.py develop
          name: setup
      - run:
          command: python tests/benchmark_throughput.py --preset minimalistic
          name: benchmark
      - run:
          command: codecov
          name: codecov

workflows:
  main:
    jobs:
      - build-and-test
