version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/3.8
    steps:
      - checkout
      - python/load-cache
      - run: pip uninstall -y pytest codecov  # temporary override for broken cache
      - run: pip install codecov pytest tqdm scikit-learn
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install -e .
          name: setup
      - run:
          command: pytest ./tests
          name: tests
      - run:
          command: python tests/benchmark_throughput.py --preset minimalistic
          name: benchmark_throughput
      - run:
          command: python tests/benchmark_dht.py
          name: benchmark_dht
      - run:
          command: codecov
          name: codecov

workflows:
  main:
    jobs:
      - build-and-test
