version: 2.1

jobs:
  build-and-test-py3_8_1:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: v1-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - '~/.cache/pip'
      - run:
          command: pip install -e .
          name: setup
      - run:
          command: pytest ./tests
          name: tests
      - run:
          command: codecov
          name: codecov
  build-and-test-py3_9_1:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: v1-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - '~/.cache/pip'
      - run:
          command: pip install -e .
          name: setup
      - run:
          command: pytest ./tests
          name: tests
      - run:
          command: codecov
          name: codecov

workflows:
  main:
    jobs:
      - build-and-test-py3_8_1
      - build-and-test-py3_9_1
