channels:
  - defaults
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - grpcio
  - grpcio-tools
  - numpy>=1.14
  - pytorch>=1.3.0
  - joblib>=0.13
  - pip
  - pip:
    - recommonmark
    - sphinx_rtd_theme
    - prefetch_generator>=1.0.1
    - umsgpack

